"""New Migration

Revision ID: 93660ad9219e
Revises: 
Create Date: 2023-10-12 13:52:30.158530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93660ad9219e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_car_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_number', sa.String(), nullable=False),
    sa.Column('trailer_number', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('load_capacity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_car_data_brand'), 'add_car_data', ['brand'], unique=False)
    op.create_index(op.f('ix_add_car_data_car_number'), 'add_car_data', ['car_number'], unique=False)
    op.create_index(op.f('ix_add_car_data_id'), 'add_car_data', ['id'], unique=False)
    op.create_index(op.f('ix_add_car_data_load_capacity'), 'add_car_data', ['load_capacity'], unique=False)
    op.create_index(op.f('ix_add_car_data_trailer_number'), 'add_car_data', ['trailer_number'], unique=False)
    op.create_table('document_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_data_id'), 'document_data', ['id'], unique=False)
    op.create_table('driver_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('other', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_data_id'), 'driver_data', ['id'], unique=False)
    op.create_index(op.f('ix_driver_data_name'), 'driver_data', ['name'], unique=False)
    op.create_index(op.f('ix_driver_data_other'), 'driver_data', ['other'], unique=False)
    op.create_index(op.f('ix_driver_data_phone_number'), 'driver_data', ['phone_number'], unique=False)
    op.create_table('driver_penalty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('penalty_amount', sa.Integer(), nullable=True),
    sa.Column('penalty_cause', sa.String(), nullable=True),
    sa.Column('penalty_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_penalty_id'), 'driver_penalty', ['id'], unique=False)
    op.create_index(op.f('ix_driver_penalty_name'), 'driver_penalty', ['name'], unique=False)
    op.create_index(op.f('ix_driver_penalty_penalty_amount'), 'driver_penalty', ['penalty_amount'], unique=False)
    op.create_index(op.f('ix_driver_penalty_penalty_cause'), 'driver_penalty', ['penalty_cause'], unique=False)
    op.create_index(op.f('ix_driver_penalty_penalty_date'), 'driver_penalty', ['penalty_date'], unique=False)
    op.create_table('driver_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('salary_amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_salary_end_date'), 'driver_salary', ['end_date'], unique=False)
    op.create_index(op.f('ix_driver_salary_id'), 'driver_salary', ['id'], unique=False)
    op.create_index(op.f('ix_driver_salary_name'), 'driver_salary', ['name'], unique=False)
    op.create_index(op.f('ix_driver_salary_salary_amount'), 'driver_salary', ['salary_amount'], unique=False)
    op.create_index(op.f('ix_driver_salary_start_date'), 'driver_salary', ['start_date'], unique=False)
    op.create_table('travel_allowances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('travel_allowances', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('amount_of_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_allowances_amount_of_days'), 'travel_allowances', ['amount_of_days'], unique=False)
    op.create_index(op.f('ix_travel_allowances_id'), 'travel_allowances', ['id'], unique=False)
    op.create_index(op.f('ix_travel_allowances_name'), 'travel_allowances', ['name'], unique=False)
    op.create_index(op.f('ix_travel_allowances_start_date'), 'travel_allowances', ['start_date'], unique=False)
    op.create_index(op.f('ix_travel_allowances_travel_allowances'), 'travel_allowances', ['travel_allowances'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_allowances_travel_allowances'), table_name='travel_allowances')
    op.drop_index(op.f('ix_travel_allowances_start_date'), table_name='travel_allowances')
    op.drop_index(op.f('ix_travel_allowances_name'), table_name='travel_allowances')
    op.drop_index(op.f('ix_travel_allowances_id'), table_name='travel_allowances')
    op.drop_index(op.f('ix_travel_allowances_amount_of_days'), table_name='travel_allowances')
    op.drop_table('travel_allowances')
    op.drop_index(op.f('ix_driver_salary_start_date'), table_name='driver_salary')
    op.drop_index(op.f('ix_driver_salary_salary_amount'), table_name='driver_salary')
    op.drop_index(op.f('ix_driver_salary_name'), table_name='driver_salary')
    op.drop_index(op.f('ix_driver_salary_id'), table_name='driver_salary')
    op.drop_index(op.f('ix_driver_salary_end_date'), table_name='driver_salary')
    op.drop_table('driver_salary')
    op.drop_index(op.f('ix_driver_penalty_penalty_date'), table_name='driver_penalty')
    op.drop_index(op.f('ix_driver_penalty_penalty_cause'), table_name='driver_penalty')
    op.drop_index(op.f('ix_driver_penalty_penalty_amount'), table_name='driver_penalty')
    op.drop_index(op.f('ix_driver_penalty_name'), table_name='driver_penalty')
    op.drop_index(op.f('ix_driver_penalty_id'), table_name='driver_penalty')
    op.drop_table('driver_penalty')
    op.drop_index(op.f('ix_driver_data_phone_number'), table_name='driver_data')
    op.drop_index(op.f('ix_driver_data_other'), table_name='driver_data')
    op.drop_index(op.f('ix_driver_data_name'), table_name='driver_data')
    op.drop_index(op.f('ix_driver_data_id'), table_name='driver_data')
    op.drop_table('driver_data')
    op.drop_index(op.f('ix_document_data_id'), table_name='document_data')
    op.drop_table('document_data')
    op.drop_index(op.f('ix_add_car_data_trailer_number'), table_name='add_car_data')
    op.drop_index(op.f('ix_add_car_data_load_capacity'), table_name='add_car_data')
    op.drop_index(op.f('ix_add_car_data_id'), table_name='add_car_data')
    op.drop_index(op.f('ix_add_car_data_car_number'), table_name='add_car_data')
    op.drop_index(op.f('ix_add_car_data_brand'), table_name='add_car_data')
    op.drop_table('add_car_data')
    # ### end Alembic commands ###
